config/routes.rb
      get :pagination
      get :others
      get :get_stats
      get :registration_form
      get :edit_tag
      get :imprint_setting
      post :update_home_settings
      post :restart_server
      post :restart_delayed_job
      post :get_stats
      post :get_user_stats
      post :update_admins
      post :update_rebrand
      post :test_email_configuration
      post :update_others
      post :update_features_enabled
      post :update_pagination
      post :delete_tag
      post :edit_tag
      post :update_imprint_setting
    end
  end

  resource :home do
    member do
      get :index
      get :feedback
      get :funding
      post :send_feedback
      get :imprint
    end
  end

  match 'funding' => 'homes#funding', :as => :match
  match 'index.html' => 'homes#index', :as => :match
  match 'index' => 'homes#index', :as => :match
  match 'my_biovel' => 'homes#my_biovel', :as => :my_biovel

  resource :favourites do
    collection do
      post :add
    end
    member do
      delete :delete
    end
  end

  resources :help, controller: 'help_documents', as: :help_documents do
    resources :attachments, controller: 'help_attachments', as: :help_attachments,only: [:create,:destroy] do
      member do
        get :download
      end
    end
    resources :images, controller: 'help_images', as: :help_images, only: [:create, :destroy]
  end
  resources :help_attachments, only: [:create,:destroy] do
    member do
      get :download
    end
  end
  resources :help_images, only: [:create, :destroy]

  resources :forum_attachments, :only => [:create, :destroy] do
    member do
      get :download
    end
  end

  resources :avatars
  resources :attachments
  resources :subscriptions
  resources :measured_items
  resources :saved_searches
  resources :uuids
  resources :compounds do
    collection do
      post :search_in_sabiork
    end
  end

  #resources :project_folders

  ### USERS AND SESSIONS ###

  resources :users do
    collection do
      get :activation_required
      get :forgot_password
      get :reset_password
      post :forgot_password
      post :hide_guide_box
      post :impersonate
      post :cancel_registration
      post :bulk_destroy
    end
    member do
      put :set_openid
      post :resend_activation_email
    end
    resources :oauth_sessions, only: [:index, :destroy]
  end

  resource :session do
    collection do
      get :index
      get :show
      get :auto_openid
    end
    member do
      get :show
    end
  end

  ### YELLOW PAGES ###

  resources :people do
    collection do
      get :typeahead
      get :register
      get :is_this_you
      get :get_work_group
      post :userless_project_selected_ajax
      post :items_for_result
      post :resource_in_tab
      post :bulk_destroy
    end
    member do
      post :check_related_items
      post :check_gatekeeper_required
      get :admin
      get :published
      get :batch_publishing_preview
      post :publish_related_items
      put :administer_update
      post :publish
      get :requested_approval_assets
      post :gatekeeper_decide
      get :gatekeeper_decision_result
      get :waiting_approval_assets
      get :select
      get :items
    end
    resources :projects,:institutions,:assays,:studies,:investigations,:models,:sops,:data_files,:presentations,:publications,:events,:samples,:specimens,:only=>[:index]
    resources :avatars do
      member do
        post :select
      end
    end
  end

  resources :projects do
    collection do
      get :request_institutions
      get :manage
      post :items_for_result
      post :resource_in_tab
    end
    member do
      get :asset_report
      get :admin
      get :admin_members
      get :admin_member_roles
      get :storage_report
      post :update_members
      get :isa_children
    end
    resources :people,:institutions,:assays,:studies,:investigations,:models,:sops,:data_files,:presentations,
              :publications,:events,:samples,:specimens,:strains,:search, :only=>[:index]
    resources :openbis_endpoints do
      member do
        post :add_dataset
      end
      collection do
        get :test_endpoint
        get :fetch_spaces
        get :show_item_count
        get :show_items
        get :show_dataset_files
        post :refresh_browse_cache
        get :browse
      end
    end
    resources :avatars do
      member do
        post :select
      end

    end
    resources :folders do
      collection do
        post :nuke
      end
      member do
        post :remove_asset
        post :display_contents
        post :move_asset_to
        post :create_folder
        post :set_project_folder_title
        post :set_project_folder_description
      end
    end
  end

  resources :institutions do
    collection do
      get :request_all
      post :items_for_result
      post :resource_in_tab
    end
    resources :people,:projects,:specimens,:only=>[:index]
    resources :avatars do
      member do
        post :select
      end
    end
  end

  ### ISA ###

  resources :investigations do
    collection do
      get :preview
      post :items_for_result
      post :resource_in_tab
    end
    resources :people,:projects,:assays,:studies,:models,:sops,:data_files,:publications,:only=>[:index]
    resources :snapshots, :only => [:show, :new, :create, :destroy] do
      member do
        get :mint_doi_confirm
        post :mint_doi
        get :download
        get :export, to: :export_preview
        post :export, to: :export_submit
      end
    end
    member do
      get :new_object_based_on_existing_one
      post :check_related_items
      post :check_gatekeeper_required
      post :publish_related_items
      post :publish
      get :published
      get :isa_children
    end
  end

  resources :studies do
    collection do
      get :preview
      post :investigation_selected_ajax
      post :items_for_result
      post :resource_in_tab
    end
    resources :snapshots, :only => [:show, :new, :create, :destroy] do
      member do
        get :mint_doi_confirm
        post :mint_doi
        get :download
        get :export, to: :export_preview
        post :export, to: :export_submit
      end
    end
    member do
      get :new_object_based_on_existing_one
      post :check_related_items
      post :check_gatekeeper_required
      post :publish_related_items
      post :publish
      get :published
      get :isa_children
    end
    resources :people,:projects,:assays,:investigations,:models,:sops,:data_files,:publications,:only=>[:index]
  end

  resources :assays do
    collection do
      get :typeahead
      get :preview
      post :items_for_result
      #MERGENOTE - these should be gets and are tested as gets, using post to fix later
      post :resource_in_tab
    end
    resources :snapshots, :only => [:show, :new, :create, :destroy] do
      member do
        get :mint_doi_confirm
        post :mint_doi
        get :download
        get :export, to: :export_preview
        post :export, to: :export_submit
      end
    end
    member do
      post :update_annotations_ajax
      post :check_related_items
      post :check_gatekeeper_required
      post :publish_related_items
      post :publish
      get :published
      get :new_object_based_on_existing_one
      get :isa_children
    end
    resources :people,:projects,:investigations,:samples, :studies,:models,:sops,:data_files,:publications,:strains,:only=>[:index]
  end


   ### ASSAY AND TECHNOLOGY TYPES ###

  resources :suggested_assay_types do
      collection do
        get :manage
      end

  end
  resources :suggested_modelling_analysis_types, :path => :suggested_assay_types, :controller => :suggested_assay_types do
     collection do
        get :manage
      end
  end
  resources :suggested_technology_types do
    collection do
      get :manage
    end
  end


  ### ASSETS ###

  resources :data_files do
    collection do
      get :typeahead
      get :preview
      get :filter
      post :test_asset_url
      post :upload_for_tool
      post :upload_from_email
      post :items_for_result
      post :resource_in_tab
    end
    member do
      get :matching_models
      get :data
      post :check_gatekeeper_required
      get :plot
      get :explore
      get :download
      get :published
      post :check_related_items
      post :publish_related_items
      post :publish
      post :request_resource
      post :update_annotations_ajax
      post :new_version
      #MERGENOTE - this is a destroy, and should be the destroy method, not post since we are not updating or creating something.
      post :destroy_version
      get :mint_doi_confirm
      post :mint_doi
      get :samples_table
      get :select_sample_type
      get :confirm_extraction
      get :extraction_status
      post :extract_samples
      delete :cancel_extraction
      get :isa_children
      get :destroy_samples_confirm
    end
    resources :studied_factors do
      collection do
        post :create_from_existing
      end
    end
    resources :content_blobs do
      member do
        get :view_pdf_content
        get :view_content
        get :get_pdf
        get :download
      end
    end
    resources :people,:projects,:investigations,:assays, :samples, :studies,:publications,:events,:only=>[:index]
  end

  resources :presentations do
    collection do
      get :typeahead
      get :preview
      post :test_asset_url
      post :items_for_result
      post :resource_in_tab
    end
    member do
      post :check_related_items
      post :check_gatekeeper_required
      get :download
      get :published
      post :publish_related_items
      post :publish
      post :request_resource
      post :update_annotations_ajax
      post :new_version
      delete :destroy_version
      get :isa_children
    end
    resources :content_blobs do
      member do
        get :view_pdf_content
        get :view_content
        get :get_pdf
        get :download

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  respond_to :html
  include Seek::PreviewHandling
  include Seek::AssetsCommon
  include Seek::IndexPager

  before_filter :samples_enabled?
  before_filter :find_index_assets, only: :index
  before_filter :find_and_authorize_requested_item, except: [:index, :new, :create, :preview]

  before_filter :auth_to_create, only: [:new, :create]

  include Seek::IsaGraphExtensions

  def index
    if @data_file || @sample_type
      respond_with(@samples)
    else
      super
    end
  end

  def new
    if params[:sample_type_id]
      @sample = Sample.new(sample_type_id: params[:sample_type_id])
      respond_with(@sample)
    else
      redirect_to select_sample_types_path
    end
  end

  def create
    @sample = Sample.new(sample_type_id: params[:sample][:sample_type_id], title: params[:sample][:title])
    update_sample_with_params
    flash[:notice] = 'The sample was successfully created.' if @sample.save
    respond_with(@sample)
  end

  def show
    @sample = Sample.find(params[:id])
    respond_with(@sample)
  end

  def edit
    @sample = Sample.find(params[:id])
    respond_with(@sample)
  end

  def update
    @sample = Sample.find(params[:id])
    update_sample_with_params
    flash[:notice] = 'The sample was successfully updated.' if @sample.save
    respond_with(@sample)
  end

  def destroy
    @sample = Sample.find(params[:id])
    if @sample.can_delete? && @sample.destroy
      flash[:notice] = 'The sample was successfully deleted.'
    else
      flash[:error] = 'It was not possible to delete the sample.'
    end
    respond_with(@sample, location: root_path)
  end

  # called from AJAX, returns the form containing the attributes for the sample_type_id
  def attribute_form
    sample_type_id = params[:sample_type_id]

    sample = Sample.new(sample_type_id: sample_type_id)

    respond_with do |format|
      format.js do
        render json: {
          form: (render_to_string(partial: 'samples/sample_attributes_form', locals: { sample: sample }))
        }
      end
    end
  end

  def filter
    @associated_samples = params[:assay_id].blank? ? [] : Assay.find(params[:assay_id]).samples
    @samples = Sample.where('title LIKE ?', "%#{params[:filter]}%").limit(20)

    respond_with do |format|
      format.html do
        render partial: 'samples/association_preview', collection: @samples,
               locals: { existing: @associated_samples }
      end
    end
  end

  private

  def update_sample_with_params
    @sample.update_attributes(params[:sample])
    update_sharing_policies @sample, params
    update_annotations(params[:tag_list], @sample)
    update_relationships(@sample, params)
  end

  def find_index_assets
    if params[:data_file_id]
      @data_file = DataFile.find(params[:data_file_id])

      unless @data_file.can_view?
        flash[:error] = 'You are not authorize to view samples from this data file'
        respond_to do |format|
          format.html { redirect_to data_file_path(@data_file) }
        end
      end

      @samples = Sample.authorize_asset_collection(@data_file.extracted_samples.includes(sample_type: :sample_attributes).all, 'view')
    elsif params[:sample_type_id]
      @sample_type = SampleType.includes(:sample_attributes).find(params[:sample_type_id])
      @samples = Sample.authorize_asset_collection(@sample_type.samples.all, 'view')
    else
      find_assets
    end
  end
end

app/helpers/samples_helper.rb
module SamplesHelper
  def sample_form_field_for_attribute(attribute)
    base_type = attribute.sample_attribute_type.base_type
    clz = "sample_attribute_#{base_type.downcase}"
    attribute_method_name = attribute.method_name
    placeholder = "e.g. #{attribute.sample_attribute_type.placeholder}" unless attribute.sample_attribute_type.placeholder.blank?

    case base_type
    when Seek::Samples::BaseType::TEXT
      text_area :sample, attribute_method_name, class: "form-control #{clz}"
    when Seek::Samples::BaseType::DATE_TIME
      calendar_date_select :sample, attribute_method_name, time: :mixed, class: "form-control  #{clz}", placeholder: placeholder
    when Seek::Samples::BaseType::DATE
      calendar_date_select :sample, attribute_method_name, time: false, class: "form-control  #{clz}", placeholder: placeholder
    when Seek::Samples::BaseType::BOOLEAN
      check_box :sample, attribute_method_name, class: "#{clz}"
    when Seek::Samples::BaseType::SEEK_STRAIN
      selected_id = @sample ? @sample.send(attribute_method_name).try(:[], 'id') : nil
      options = option_groups_from_collection_for_select(Organism.all, :strains, :title, :id, :title, selected_id)
      select(:sample, attribute_method_name, options, { include_blank: !attribute.required? }, class: "form-control #{clz}")
    when Seek::Samples::BaseType::CV
      terms = attribute.sample_controlled_vocab.sample_controlled_vocab_terms
      collection_select :sample, attribute_method_name, terms, :label, :label,
                        { include_blank: !attribute.required? }, class: "form-control #{clz}"
    when Seek::Samples::BaseType::SEEK_SAMPLE
      terms = Sample.authorize_asset_collection(attribute.linked_sample_type.samples, :view)
      collection_select :sample, attribute_method_name, terms, :id, :title,
                        { include_blank: !attribute.required? }, class: "form-control #{clz}"
    else
      text_field :sample, attribute_method_name, class: "form-control #{clz}", placeholder: placeholder
    end
  end

  def authorised_samples(projects = nil)
    authorised_assets(Sample, projects)
  end

  def sample_attribute_title_and_unit(attribute)
    title = attribute.title
    if (unit = attribute.unit) && !unit.dimensionless?
      title += " ( #{unit} )"
    end
    title
  end

  def display_attribute(sample, attribute, options = {})
    value = sample.get_attribute(attribute.hash_key)
    if value.blank?
      text_or_not_specified(value)
    else
      case attribute.sample_attribute_type.base_type
      when Seek::Samples::BaseType::DATE
        Date.parse(value).strftime('%e %B %Y')
      when Seek::Samples::BaseType::DATE_TIME
        DateTime.parse(value).strftime('%e %B %Y %H:%M:%S')
      when Seek::Samples::BaseType::SEEK_STRAIN
        seek_strain_attribute_display(value)
      when Seek::Samples::BaseType::SEEK_SAMPLE
        seek_sample_attribute_display(value)
      else
        default_attribute_display(attribute, options, sample, value)
      end
    end
  end

  def seek_sample_attribute_display(value)
    sample = Sample.find_by_id(value)
    if sample
      if sample.can_view?
        link_to sample.title, sample
      else
        content_tag :span, 'Hidden', class: 'none_text'
      end
    else
      content_tag :span, 'Not found', class: 'none_text'
    end
  end

  def default_attribute_display(attribute, options, sample, value)
    if options[:link] && attribute.is_title
      link_to(value, sample)
    else
      text_or_not_specified(value, auto_link: options[:link])
    end
  end

  def seek_strain_attribute_display(value)
    if value && value['id']
      if value['title']
        link_to(value['title'], strain_path(value['id']))
      else
        content_tag(:span, value['id'], class: 'none_text')
      end
    else
      content_tag(:span, 'Not specified', class: 'none_text')
    end
  end
end

app/views/samples/_associate_sample.html.erb
<%
  return unless Seek::Config.samples_enabled
  resource_text ||= text_for_resource(resource)

  assay_assets = resource.assay_assets.where(asset_type: 'Sample').includes(:asset)

  samples = Sample.joins(:projects).where(projects: { id: current_user.person.projects.map(&:id) }).limit(100).order('updated_at DESC')
  authorized_samples = Sample.authorize_asset_collection(samples, :view)

  data_files = DataFile.with_extracted_samples.all_authorized_for('view').select { |d| d.extracted_samples.any? }.first(20)

  if params[:samples] && params[:samples].any?
    collapse_panel = false
    associated_samples_json = associations_json_from_params(Sample, params[:samples])
  else
    collapse_panel = assay_assets.empty?
    associated_samples_json = associations_json_from_assay_assets(assay_assets)
  end

-%>

<%= folding_panel("Samples", collapse_panel, :body_options => {:id => 'associate_sample_fold_content'},
                  :help_text => "Here you associate Samples in SEEK to this #{resource_text}.") do %>

    <p>The following Samples are involved in this <%= resource_text -%>:</p>

    <%= associations_list_group('sample_to_list', 'direction.value', associated_samples_json) do %>
        <div class="row">
          <div class="col-md-4">
            <h3>Incoming</h3>
            <%= associations_list('incoming-sample-list', 'associations/sample', '',
                                  empty_text: 'No incoming samples',
                                  'data-multilist-group-value' => AssayAsset::Direction::INCOMING) %>
          </div>
          <div class="col-md-4">
            <h3>Outgoing</h3>
            <%= associations_list('outgoing-sample-list', 'associations/sample', '',
                                  empty_text: 'No outgoing samples',
                                  'data-multilist-group-value' => AssayAsset::Direction::OUTGOING) %>
          </div>
          <div class="col-md-4">
            <h3>No direction</h3>
            <%= associations_list('other-sample-list', 'associations/sample', '',
                                  empty_text: 'No other samples',
                                  'data-multilist-group-value' => AssayAsset::Direction::NODIRECTION) %>
          </div>
        </div>
    <% end %>

    <hr/>

    <%= association_selector('sample_to_list', 'Add individual samples', 'Select samples') do %>
        <label>Select samples</label>
        <%= filterable_association_select(filter_samples_path(:assay_id => resource.id), :multiple => true) do %>
            <%= render :partial => 'samples/association_preview',
                       :collection => authorized_samples,
                       :locals => { :existing => resource.samples }
            %>
        <% end %>

        <hr/>

        <div class="form-group">
          <label>Select sample direction</label>
          <%= select_tag(:direction, direction_options, :class => 'form-control', :autocomplete => 'off',
                         'data-role' => 'seek-association-common-field') %>
        </div>
    <% end %>

    <%= button_link_to('Add samples from data file', 'add', '#', 'data-toggle' => 'modal', 'data-target' => "#AddSamplesFromDataFileModal") %>
    <%= modal(id: 'AddSamplesFromDataFileModal', size: 'xl', 'data-role' => 'seek-wizard') do %>
        <%= modal_header('Add samples from data file') %>
        <%= modal_body do %>
            <div data-role="seek-wizard-nav"></div>
            <div data-role="seek-wizard-step" data-step-name="Select data file" id="samples-select-data-file">
              <label>Select data file</label>
              <%= filterable_association_select(filter_data_files_path(with_samples: true)) do %>
                  <%= render :partial => 'data_files/association_preview',
                             :collection => data_files,
                             :locals => { :existing => resource.samples }
                  %>
              <% end %>
            </div>
            <div data-role="seek-wizard-step" data-step-name="Select samples">
              <label>Select samples</label>
              <div id="data-file-samples-table">
                <%= image('spinner') %>
              </div>
            </div>
            <div data-role="seek-wizard-step" data-step-name="Select sample direction">
              <div class="form-group">
                <label>Select sample direction</label>
                <%= select_tag(:direction, direction_options, :class => 'form-control', :autocomplete => 'off',
                               'data-role' => 'seek-association-common-field') %>
              </div>
            </div>
        <% end %>
        <%= modal_footer do %>
            <a data-role="seek-wizard-next-btn" href="#" class="pull-right btn btn-default">Next</a>
            <a data-role="seek-wizard-prev-btn" href="#" class="pull-left btn btn-default">Previous</a>
            <%= confirm_association_button('Add samples', id: 'add-batch-sample-btn', style: 'display: none',
                                           class: 'btn btn-primary pull-right', 'data-dismiss' => 'modal') %>
        <% end %>
    <% end %>
    <%= button_link_to('Clear all samples', 'destroy', '#', id: 'clear-all-samples-btn') %>
<% end %>

<script>
  var wizard;
  $j(document).ready(function () {
    // Reset the "Add individual samples" modal after it is closed
    $j('#modalAddIndividualSamples').on('hidden.bs.modal', function () {
      var filterField = $j('[data-role="seek-association-filter"]', $j(this));
      filterField.val('');
      Associations.filter(filterField[0]);
      $j('select', $j(this)).val('0');
    });

    var samplesList = $j('#sample_to_list').data('associationList');
    var batchSamplesForm = new Associations.Form(samplesList, $j('#AddSamplesFromDataFileModal'));
    $j('#AddSamplesFromDataFileModal :input[data-role="seek-association-common-field"]').each(function () {
      $j(this).data('attributeName', this.name);
      this.name = '';
      batchSamplesForm.commonFieldElements.push($j(this));
    });

    var samplesTable;

    function initSamplesTable() {
      samplesTable = Samples.initTable($j('#data-file-samples-table'), true);
      // When at least one sample is selected, unlock step 3
      var handleRowSelect = function ( e, dt, type, indexes ) {
        var selectedRowData = samplesTable.rows({ selected: true }).data();

        batchSamplesForm.selectedItems = [];
        for(var i = 0; i < selectedRowData.length; i++) {
          batchSamplesForm.selectedItems.push({
            id: selectedRowData[i].id,
            title: selectedRowData[i].title
          });
        }

        if(selectedRowData.length > 0) {
          wizard.step(3).unlock();
        } else {
          wizard.step(3).lock();
        }
      };
      samplesTable.on('select', handleRowSelect);
      samplesTable.on('deselect', handleRowSelect);
    }

    initSamplesTable();

    $j('#add-batch-sample-btn').click(function () {
      batchSamplesForm.submit();
    });
    $j('#clear-all-samples-btn').click(function () {
      if(confirm("Are you sure you wish to remove all samples from this assay?")) {
        samplesList.removeAll();
      }
      return false;
    });

    // Wizard steps
    wizard = new Wizards.Wizard($j('#AddSamplesFromDataFileModal'));

    // On final step, show the confirm button
    wizard.step(3).onShow = function () {
      $j('#add-batch-sample-btn').show();
    };
    wizard.step(3).onHide = function () {
      $j('#add-batch-sample-btn').hide();
    };

    // Reset the wizard when the modal is closed
    $j('#AddSamplesFromDataFileModal').on('hide.bs.modal', function () {
      var filterField = $j('[data-role="seek-association-filter"]', $j(this));
      filterField.val('');
      Associations.filter(filterField[0]);
      samplesTable.rows().deselect();
      wizard.reset();
    });

    $j('#samples-select-data-file').on('click', '.selectable[data-role="seek-association-candidate"]', function () {
      var candidate = $j(this);
      candidate.spinner('add');
      $j.ajax('/data_files/'+$j(this).data('associationId')+'/samples_table', {
            success: function (data) {
              $j('#data-file-samples-table').html(data);
              initSamplesTable();
              wizard.step(2).unlock();
              wizard.gotoStep(2);
              candidate.spinner('remove');
            }
          }
      );

      return false;
    })
  });
</script>

app/views/samples/_association_preview.html.erb
<%= link_to '#', :class => "list-group-item selectable #{'list-group-item-success' if existing.include?(association_preview)}",
            'data-role' => 'seek-association-candidate',
            'data-association-id' => association_preview.id,
            'data-association-title' => association_preview.title do %>
    <%= association_preview.title %>
    <small>(<%= association_preview.sample_type.title %>)</small>
<% end %>

app/views/samples/_attribute_fields.html.erb
<% sample_type.sample_attributes.each do |attribute| %>
    <div class="form-group <%= 'date-select' if ['Date','DateTime'].include?(attribute.sample_attribute_type.base_type) %>">
      <label><%= sample_attribute_title_and_unit(attribute) %></label><%= required_span if attribute.required? %>
      <%= sample_form_field_for_attribute(attribute) %>
    </div>
<% end %>

app/views/samples/_attribute_values.html.erb
<% sample.sample_type.sample_attributes.each do |attribute| %>
    <p>
      <label><%= sample_attribute_title_and_unit(attribute) %>:</label>
      <%= display_attribute(sample, attribute, link: true) %>
    </p>
<% end %>

app/views/samples/_form.html.erb
<div class="asset_form">
  <%= render partial: 'sample_error_messages', locals: { object: @sample } %>

  <p id="sample-type">
    <label>Sample type: </label> <%= link_to(h(@sample.sample_type.title), @sample.sample_type) %>
    <% if @sample.new_record? %>
      <span style="font-size:smaller">
        (<%= link_to('change', select_sample_types_path) %>)
      </span>
    <% end %>
    <%= f.hidden_field(:sample_type_id) %>
  </p>

  <div id="sample_attributes">
    <%= render :partial=>"sample_attributes_form",:locals=>{sample:@sample} %>
  </div>

  <div id="sample_extra_details">
    <%= render :partial => "projects/project_selector", :locals => { :resource => @sample,:allow_nil=> false} -%>
    <% if @sample.can_manage? -%>
        <%= render :partial => "assets/asset_form_bottom", :locals=>{:f=>f,attribution_enable:false,show_publications:false,sharing_link:false} %>
    <% end %>
  </div>
  <%= preview_permission_popup_link(@sample)-%>

  <%= f.submit (@sample.new_record? ? "Create" : "Update"), :class => 'btn btn-primary',:id=>'sample_submit_btn',disabled:@sample.sample_type.nil? %>
    or
  <%= cancel_button(@sample.new_record? ? sample_type_path(@sample.sample_type) : sample_path(@sample)) %>
</div>

<script>

    $j('#sample_submit_btn').on('click', function() {
        previewPermissions();
        return(false);
    });

</script>

app/views/samples/_resource_list_item.html.erb
<%= render :partial=>"assets/resource_list_item_contributor_and_creators",:object=>resource -%>

app/views/samples/_resource_preview.html.erb
<strong>Preview Not Yet Implemented</strong>

app/views/samples/_sample_attributes_form.html.erb
<% if sample.sample_type %>

    <%= render :partial => "attribute_fields", :locals => {:sample_type => sample.sample_type} %>

<% end %>

app/views/samples/_sample_error_messages.html.erb
<% if object.errors.any? %>
    <div id="errorExplanation" class="errorExplanation">
      <h2><%= pluralize(object.errors.count, 'error') %> prohibited this sample from being saved</h2>
      <p>There were problems with the following fields:</p>
      <ul>
        <% object.errors.each do |attr, msg| %>
            <li><%= attr.to_s.sub(SampleAttribute::METHOD_PREFIX, '').humanize %> <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/samples/_samples_graph.html.erb
<%
  elements = cytoscape_elements(Seek::SampleGraphGenerator.new(sample).generate)
  # reduced_elements = cytoscape_elements(Seek::SampleGraphGenerator.new(sample).generate(1))
%>

<%= render partial: 'general/cytoscape_graph', locals: { elements: elements, root_item: sample } %>

app/views/samples/edit.html.erb
<h1>Edit Sample</h1>

<%= form_for(@sample) do |f| %>
    <%= render :partial => "form", :locals => { :f => f } -%>
<% end %>

app/views/samples/new.html.erb
<h1>New Sample</h1>

<%= form_for(@sample) do |f| %>
    <%= render :partial => "form", :locals => {:f => f} -%>
<% end %>

app/views/samples/show.html.erb
<%= render :partial => "general/item_title", :locals => {:item => @sample, :buttons_partial => 'assets/asset_buttons'} %>



<div class="row">
  <div class="col-md-9 col-sm-8 box_about_actor">

    <div class="row">
      <div class="col-md-6">
        <p>
          <label>Sample type:</label>
          <%= link_to @sample.sample_type.title,@sample.sample_type %>
        </p>
        <% if @sample.originating_data_file %>
            <p>
              <label>Source data:</label>
              <%= link_to @sample.originating_data_file.title, @sample.originating_data_file %>
            </p>
        <% end %>
        <%= render :partial => "attribute_values", :locals => {:sample => @sample} %>
      </div>
    </div>
    <%# render :partial => "samples/samples_graph", :locals => {:sample => @sample} %>
  </div>

  <div class="col-md-3 col-sm-4">
    <%= render :partial=>"assets/resource_main_content_right",:locals => { :resource => @sample } %>
  </div>
</div>


<%= render :partial=>"general/items_related_to",:object => @sample %>