config/routes.rb
SEEK::Application.routes.draw do

  mount MagicLamp::Genie, :at => (SEEK::Application.config.relative_url_root || "/") + 'magic_lamp'  if defined?(MagicLamp)
  mount Teaspoon::Engine, :at => (SEEK::Application.config.relative_url_root || "/") + "teaspoon" if defined?(Teaspoon)

  mount TavernaPlayer::Engine, :at => (SEEK::Application.config.relative_url_root || "/")

  resources :scales do
    collection do
      post :search
      post :search_and_lazy_load_results
    end
  end


  ### GENERAL PAGES ###

  root :to => "homes#index"

  resource :admin do
    member do
      get :show
      get :tags
      get :features_enabled
      get :rebrand
      get :home_settings
      get :pagination
      get :others
      get :get_stats
      get :registration_form
      get :edit_tag
      get :imprint_setting
      post :update_home_settings
      post :restart_server
      post :restart_delayed_job
      post :get_stats
      post :get_user_stats
      post :update_admins
      post :update_rebrand
      post :test_email_configuration
      post :update_others
      post :update_features_enabled
      post :update_pagination
      post :delete_tag
      post :edit_tag
      post :update_imprint_setting
    end
  end

  resource :home do
    member do
      get :index
      get :feedback
      get :funding
      post :send_feedback
      get :imprint
    end
  end

  match 'funding' => 'homes#funding', :as => :match
  match 'index.html' => 'homes#index', :as => :match
  match 'index' => 'homes#index', :as => :match
  match 'my_biovel' => 'homes#my_biovel', :as => :my_biovel

  resource :favourites do
    collection do
      post :add
    end
    member do
      delete :delete
    end
  end

  resources :help, controller: 'help_documents', as: :help_documents do
    resources :attachments, controller: 'help_attachments', as: :help_attachments,only: [:create,:destroy] do
      member do
        get :download
      end
    end
    resources :images, controller: 'help_images', as: :help_images, only: [:create, :destroy]
  end
  resources :help_attachments, only: [:create,:destroy] do
    member do
      get :download
    end
  end
  resources :help_images, only: [:create, :destroy]

  resources :forum_attachments, :only => [:create, :destroy] do
    member do
      get :download
    end
  end

  resources :avatars
  resources :attachments
  resources :subscriptions
  resources :measured_items
  resources :saved_searches
  resources :uuids
  resources :compounds do
    collection do
      post :search_in_sabiork
    end
  end

  #resources :project_folders

  ### USERS AND SESSIONS ###

  resources :users do
    collection do
      get :activation_required
      get :forgot_password
      get :reset_password
      post :forgot_password
      post :hide_guide_box
      post :impersonate
      post :cancel_registration
      post :bulk_destroy
    end
    member do
      put :set_openid
      post :resend_activation_email
    end
    resources :oauth_sessions, only: [:index, :destroy]
  end

  resource :session do
    collection do
      get :index
      get :show
      get :auto_openid
    end
    member do
      get :show
    end
  end

  ### YELLOW PAGES ###

  resources :people do
    collection do
      get :typeahead
      get :register
      get :is_this_you
      get :get_work_group
      post :userless_project_selected_ajax
      post :items_for_result
      post :resource_in_tab
      post :bulk_destroy
    end
    member do
      post :check_related_items
      post :check_gatekeeper_required
      get :admin
      get :published
      get :batch_publishing_preview
      post :publish_related_items
      put :administer_update
      post :publish
      get :requested_approval_assets
      post :gatekeeper_decide
      get :gatekeeper_decision_result
      get :waiting_approval_assets
      get :select
      get :items
    end
    resources :projects,:institutions,:assays,:studies,:investigations,:models,:sops,:data_files,:presentations,:publications,:events,:samples,:specimens,:only=>[:index]
    resources :avatars do
      member do
        post :select
      end
    end
  end

  resources :projects do
    collection do
      get :request_institutions
      get :manage
      post :items_for_result
      post :resource_in_tab
    end
    member do
      get :asset_report
      get :admin
      get :admin_members
      get :admin_member_roles
      get :storage_report
      post :update_members
      get :isa_children
    end
    resources :people,:institutions,:assays,:studies,:investigations,:models,:sops,:data_files,:presentations,
              :publications,:events,:samples,:specimens,:strains,:search, :only=>[:index]
    resources :openbis_endpoints do
      member do
        post :add_dataset
      end
      collection do
        get :test_endpoint
        get :fetch_spaces
        get :show_item_count
        get :show_items
        get :show_dataset_files
        post :refresh_browse_cache
        get :browse
      end
    end
    resources :avatars do
      member do
        post :select
      end

    end
    resources :folders do
      collection do
        post :nuke
      end
      member do
        post :remove_asset
        post :display_contents
        post :move_asset_to
        post :create_folder
        post :set_project_folder_title
        post :set_project_folder_description
      end
    end
  end

  resources :institutions do
    collection do
      get :request_all
      post :items_for_result
      post :resource_in_tab
    end
    resources :people,:projects,:specimens,:only=>[:index]
    resources :avatars do
      member do
        post :select
      end
    end
  end

  ### ISA ###

  resources :investigations do
    collection do
      get :preview
      post :items_for_result
      post :resource_in_tab
    end
    resources :people,:projects,:assays,:studies,:models,:sops,:data_files,:publications,:only=>[:index]
    resources :snapshots, :only => [:show, :new, :create, :destroy] do
      member do
        get :mint_doi_confirm
        post :mint_doi
        get :download
        get :export, to: :export_preview
        post :export, to: :export_submit
      end
    end
    member do
      get :new_object_based_on_existing_one
      post :check_related_items
      post :check_gatekeeper_required
      post :publish_related_items
      post :publish
      get :published
      get :isa_children
    end
  end

  resources :studies do
    collection do
      get :preview
      post :investigation_selected_ajax
      post :items_for_result
      post :resource_in_tab
    end
    resources :snapshots, :only => [:show, :new, :create, :destroy] do
      member do
        get :mint_doi_confirm
        post :mint_doi
        get :download
        get :export, to: :export_preview
        post :export, to: :export_submit
      end
    end
    member do
      get :new_object_based_on_existing_one
      post :check_related_items
      post :check_gatekeeper_required
      post :publish_related_items
      post :publish
      get :published
      get :isa_children
    end
    resources :people,:projects,:assays,:investigations,:models,:sops,:data_files,:publications,:only=>[:index]
  end

  resources :assays do
    collection do
      get :typeahead
      get :preview
      post :items_for_result
      #MERGENOTE - these should be gets and are tested as gets, using post to fix later
      post :resource_in_tab
    end
    resources :snapshots, :only => [:show, :new, :create, :destroy] do
      member do
        get :mint_doi_confirm
        post :mint_doi
        get :download
        get :export, to: :export_preview
        post :export, to: :export_submit
      end
    end
    member do
      post :update_annotations_ajax
      post :check_related_items
      post :check_gatekeeper_required
      post :publish_related_items
      post :publish
      get :published
      get :new_object_based_on_existing_one
      get :isa_children
    end
    resources :people,:projects,:investigations,:samples, :studies,:models,:sops,:data_files,:publications,:strains,:only=>[:index]
  end


   ### ASSAY AND TECHNOLOGY TYPES ###

  resources :suggested_assay_types do
      collection do
        get :manage
      end

  end
  resources :suggested_modelling_analysis_types, :path => :suggested_assay_types, :controller => :suggested_assay_types do
     collection do
        get :manage
      end
  end
  resources :suggested_technology_types do
    collection do
      get :manage
    end
  end


  ### ASSETS ###

  resources :data_files do
    collection do
      get :typeahead
      get :preview
      get :filter
      post :test_asset_url
      post :upload_for_tool
      post :upload_from_email
      post :items_for_result
      post :resource_in_tab
    end
    member do
      get :matching_models
      get :data
      post :check_gatekeeper_required
      get :plot
      get :explore
      get :download
      get :published
      post :check_related_items
      post :publish_related_items
      post :publish
      post :request_resource
      post :update_annotations_ajax
      post :new_version
      #MERGENOTE - this is a destroy, and should be the destroy method, not post since we are not updating or creating something.
      post :destroy_version
      get :mint_doi_confirm
      post :mint_doi
      get :samples_table
      get :select_sample_type
      get :confirm_extraction
      get :extraction_status
      post :extract_samples
      delete :cancel_extraction
      get :isa_children
      get :destroy_samples_confirm
    end
    resources :studied_factors do
      collection do
        post :create_from_existing
      end
    end
    resources :content_blobs do
      member do
        get :view_pdf_content
        get :view_content
        get :get_pdf
        get :download
      end
    end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController

  include Seek::IndexPager
  include Seek::AssetsCommon

  before_filter :find_assets, :only=>[:index]
  before_filter :find_and_authorize_requested_item, :only=>[:edit, :update, :destroy, :show,:new_object_based_on_existing_one]

  #project_membership_required_appended is an alias to project_membership_required, but is necesary to include the actions
  #defined in the application controller
  before_filter :project_membership_required_appended, :only=>[:new_object_based_on_existing_one]

  before_filter :check_assays_are_not_already_associated_with_another_study,:only=>[:create,:update]

  include Seek::Publishing::PublishingCommon

  include Seek::AnnotationCommon

  include Seek::BreadCrumbs

  include Seek::IsaGraphExtensions

  def new_object_based_on_existing_one
    @existing_study =  Study.find(params[:id])

    if @existing_study.can_view?
      @study = @existing_study.clone_with_associations
      unless @existing_study.investigation.can_edit?
        @study.investigation=nil
        flash.now[:notice] = "The #{t('investigation')} associated with the original #{t('study')} cannot be edited, so you need to select a different #{t('investigation')}"
      end
      render :action => "new"
    else
      flash[:error]="You do not have the necessary permissions to copy this #{t('study')}"
      redirect_to study_path(@existing_study)
    end

  end

  def new
    @study = Study.new
    @study.create_from_asset = params[:create_from_asset]
    @study.new_link_from_assay = params[:new_link_from_assay]
    investigation = nil
    investigation = Investigation.find(params[:investigation_id]) if params[:investigation_id]
    
    if investigation
      if investigation.can_edit?
        @study.investigation = investigation
      else
        flash.now[:error] = "You do not have permission to associate the new #{t('study')} with the #{t('investigation')} '#{investigation.title}'."
      end
    end
    investigations = Investigation.all.select(&:can_view?)
    respond_to do |format|
      if investigations.blank?
       flash.now[:notice] = "No #{t('investigation')} available, you have to create a new one before creating your Study!"
      end
      format.html
    end
  end

  def edit
    @study=Study.find(params[:id])
    respond_to do |format|
      format.html
      format.xml
    end
  end

  
  def update
    @study=Study.find(params[:id])

    @study.attributes = params[:study]

    update_sharing_policies @study,params

    respond_to do |format|
      if @study.save
        update_scales @study
        update_relationships(@study, params)

        flash[:notice] = "#{t('study')} was successfully updated."
        format.html { redirect_to(@study) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @study.errors, :status => :unprocessable_entity }
      end
    end
  end

  def show
    @study=Study.find(params[:id])
    @study.create_from_asset = params[:create_from_asset]
    respond_to do |format|
      format.html
      format.xml
      format.rdf { render :template=>'rdf/show'}
    end

  end

  def create
    @study = Study.new(params[:study])

    update_sharing_policies @study,params


  if @study.save
    update_scales @study
    update_relationships(@study, params)

    if @study.new_link_from_assay=="true"
      render :partial => "assets/back_to_singleselect_parent",:locals => {:child=>@study,:parent=>"assay"}
    else
      respond_to do |format|
        flash[:notice] = "The #{t('study')} was successfully created.<br/>".html_safe
        if @study.create_from_asset=="true"
          flash.now[:notice] << "Now you can create new #{t('assays.assay')} by clicking -Add an #{t('assays.assay')}- button".html_safe
          format.html { redirect_to study_path(:id=>@study,:create_from_asset=>@study.create_from_asset) }
        else
        format.html { redirect_to study_path(@study) }
        format.xml { render :xml => @study, :status => :created, :location => @study }
        end
      end
    end
  else
    respond_to do |format|
        format.html {render :action=>"new"}
        format.xml  { render :xml => @study.errors, :status => :unprocessable_entity }
      end
    end
  end

  def investigation_selected_ajax

    if investigation_id = params[:investigation_id] and params[:investigation_id]!="0"
      investigation = Investigation.find(investigation_id)
      people=investigation.projects.collect(&:people).flatten
    end

    people||=[]

    render :update do |page|
      page.replace_html "person_responsible_collection",:partial=>"studies/person_responsible_list",:locals=>{:people=>people}
    end

  end

  def check_assays_are_not_already_associated_with_another_study
    assay_ids=params[:study][:assay_ids]
    study_id=params[:id]    
    if (assay_ids)
      valid = !assay_ids.detect do |a_id|
        a=Assay.find(a_id)
        !a.study.nil? && a.study_id.to_s!=study_id
      end
      if !valid
        unless valid
          error("Cannot add an #{t('assays.assay')} already associated with a Study", "is invalid (invalid #{t('assays.assay')})")
          return false
        end
      end
    end
  end
end

app/helpers/studies_helper.rb
module StudiesHelper
  # generates the HTML to display the project avatar and named link
  def related_project_avatar(project)
    project_title = h(project.title)
    project_url = project_path(project)
    image_tag = avatar(project, 60, false, project_url, project_title, false)
    project_link = link_to project_title, project_url, alt: project_title

    (image_tag + "<p style='margin: 0; text-align: center;'>#{project_link}</p>").html_safe
  end

  def sorted_measured_items
    items = MeasuredItem.all
    items.sort { |a, b| a.title <=> b.title }
  end

  def studies_link_list(studies, sorted = true)
    # FIXME: make more generic and share with other model link list helper methods
    studies.compact! # remove nil items
    return "<span class='none_text'>Not associated with any #{t('study').pluralize}</span>".html_safe if studies.empty?

    result = ''
    studies = studies.sort { |a, b| a.title <=> b.title } if sorted
    studies.each do |study|
      if study.can_view?
        result += link_to study.title.capitalize, study
      else
        result += hidden_items_html [study]
      end
      result += ' | ' unless studies.last == study
    end
    result.html_safe
  end

  def authorised_studies(projects = nil)
    authorised_assets(Study, projects, 'view')
  end
end

app/views/studies/_buttons.html.erb
<%= render :partial => "subscriptions/subscribe", :locals => {:object => item} %>

<% if logged_in_and_member? %>
    <%= button_link_to("New #{t('study')} based on this one", 'new', new_object_based_on_existing_one_study_path(item,:controller_name=>"studies")) %>
<% end %>

<% if item.can_edit? -%>
  <%= button_link_to("Add an #{t('assays.assay')}", 'new', new_assay_path(:study_id=>item,:create_from_asset=>item.create_from_asset)) -%>
<% end -%>

<%= admin_dropdown do %>
    <% if item.can_manage? -%>
        <li><%= image_tag_for_key('manage', edit_study_path, nil, nil, "Manage #{t('study')}") -%></li>
        <%= render :partial => 'snapshots/new_snapshot_link', :locals => { :item => item } %>
    <% elsif item.can_edit?-%>
        <li><%= image_tag_for_key('edit', edit_study_path, "Edit #{t('study')}", nil, "Edit #{t('study')}") -%></li>
    <% end -%>

    <%= delete_icon item,current_user -%>
<% end -%>

app/views/studies/_form.html.erb
<%= error_messages_for :study %>

<%= f.hidden_field :create_from_asset %>
<%= f.hidden_field :new_link_from_assay -%>

<div class="form-group">
  <label>Title <span class="required">*</span></label>
  <%= f.text_field :title,:class=>"form-control" %>
</div>

<div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, :rows=>5, :class=>"form-control" %>
</div>

<div class="form-group">
  <%= f.label "Experimentalist(s)" %>
  <%= f.text_area :experimentalists, :rows => 1, :class=>"form-control" %>
</div>

<%= folding_panel("#{t('investigation')} details") do %>
    <label><%= t('investigation') %></label><span class="required">*</span>
    <%=link_to "New #{t('investigation')}?",new_investigation_path(:new_link_from_study=>true), :onclick => "window.open(this.href);return false;"%><br/>
    <div id="investigation_collection">
      <%= render :partial=>"studies/investigation_list",:locals=>{:investigations=>Investigation.all.select {|i|current_user.person.member_of? i.projects}} -%>
    </div>

    <%= f.label t('person_responsible').capitalize %>
    <div id="person_responsible_collection">
      <% people = @study.investigation ? @study.investigation.projects.collect(&:people).flatten : [] -%>
      <%= render :partial=>"studies/person_responsible_list",:locals=>{:people=>people} -%>
    </div>
<% end %>

<%  existing_creators = @study.creators
    existing_creators =  [current_user.person] if existing_creators.blank?
%>

<%= render :partial => "assets/author_form", :locals => {:resource_type => t('study'), # this is only for presentation, not for any processing
                                                         :existing_creators => existing_creators,
                                                         :other_creators => @study.other_creators} -%>

<% if show_scales? %>
    <%= render :partial => "scales/scales_selector",:locals=>{:object=>@study} %>
<% end %>

<%= render :seek_partial=>"sharing/form" if @study.can_manage? -%>

<%= render :partial => "assets/associate_publication", :locals => { :resource_type => t('study'),
                                                                        :related_publications => @study.publications} -%>

<script type="text/javascript">
    var CREATE_INVESTIGATION_LINK = "<%= create_investigation_url %>";
</script>

<%
   button_text=action==:edit ? "Update" : "Create"
   disabled_text=action==:edit ? "Updating..." : "Creating..."
%>
<% if @study.can_manage? %>
    <%= preview_permission_popup_link(@study)-%>
    <%= f.submit button_text, :id => "study_submit_btn",
                 :onclick => "javascript: previewPermissions();return(false);",
                 :class => 'btn btn-primary'-%>
<% else %>
    <%= f.submit button_text, :disable_with=>disabled_text, :id => "study_submit_btn",
                 :onclick => "javascript: $('study_submit_btn').form.submit();return(false);",
                 :class => 'btn btn-primary'-%>
<% end %>
 or <%= cancel_button(@study.id ? study_path(@study.id) : studies_path) -%>

<script>
  var projectsLookup = <%= Hash[Investigation.all_authorized_for(:edit).map { |i| [i.id, i.projects.map { |p| { id: p.id, title: p.title } }] }].to_json.html_safe -%>;

  $j(document).ready(function () {
    $j('#study_investigation_id').change(function () {
      Sharing.removeMandatoryProjectPermissions();
      if ($j(this).val()) {
        var projects = projectsLookup[parseInt($j(this).val())];
        if (projects && projects.length) {
          for (var i = 0; i < projects.length; i++) {
            Sharing.addPermissionForProject(projects[i]);
          }
        }
      }
    });
  });
</script>

app/views/studies/_investigation_list.html.erb
<%
 investigations = investigations | [@study.investigation] if @study.investigation
 investigations = investigations.select &:can_edit?
 investigation_value=(@study && @study.investigation) ? @study.investigation.id : 0
 investigation_options = [["Select an #{t('investigation')}..",0]]|investigations.collect{|t| [h(t.title),t.id]}
%>

<%= select_tag :study_investigation_id,
  options_for_select(investigation_options,investigation_value),
  {
    :disabled=>(investigations.nil? || investigations.empty?),
    :name=>"study[investigation_id]",
    :onchange=>remote_function(
          :url=>investigation_selected_ajax_studies_path,
          :with=>"'investigation_id='+this.value",
          :before=>"show_ajax_loader('person_responsible_collection')"
        ),
    :class => 'form-control'
  }
-%>

app/views/studies/_person_responsible_list.html.erb
<% person_value=(@study && @study.person_responsible) ? @study.person_responsible.id : 0 %>
<% person_value=current_user.person.id if (person_value==0 && people.include?(current_user.person)) %>
<% people_options = [["Nobody",0]]|people.collect{|p| [h(p.name),p.id]} %>

<%= select_tag :study_person_responsible_id,
  options_for_select(people_options,person_value),
  {
    :disabled=>(people.nil? || people.empty?),
    :name=>"study[person_responsible_id]",
    :class => 'form-control'
  }
-%>

app/views/studies/_resource_list_item.html.erb
<%= list_item_description h(resource.description) %>

<div class="row">
  <div class="col-sm-6">
    <%= list_item_authorized_attribute t('person_responsible').capitalize, resource.person_responsible %>
  </div>

  <div class="col-sm-6 hidden-xs">
    <%= list_item_authorized_list [resource.investigation], t('investigation'), true, 50, true  %>
  </div>
</div>

<%= list_item_authorized_list resource.assays, t('assays.assay').pluralize %>
<div class="hidden-xs">
  <%= scales_list_for_list_item resource %>
</div>

app/views/studies/_resource_preview.html.erb
<%= list_item_title resource %>

<%= list_item_attribute "ID", resource.id %>

<%= list_item_authorized_list([resource.investigation], t('investigation').pluralize, true, 50, true)%>

<%= list_item_authorized_list(resource.assays, t('assay').pluralize, true, 50, true)%>

<%= list_item_attribute t('contributor').capitalize, resource.contributor.try(:person).try(:name), resource.contributor %>

<%= render :partial => 'projects/show_project_relationship', :locals => {:resource => resource, :list_item => true} %>

app/views/studies/edit.html.erb
<h1>Edit <%= t('study') %></h1>

<div class="show_basic">
	<%= form_for @study do |f| %>
	  <%= render :partial => "form", :locals => { :f => f, :action=>:edit } -%>
	<% end -%>
</div>

app/views/studies/index.html.erb
<%= render :partial=> "general/index" %>

app/views/studies/new.html.erb
<script type="text/javascript">
  var CREATE_INVESTIGATION_PATH='<%= create_investigation_path %>';
</script>
<% investigations = Investigation.all.select &:can_view? -%>
<% if investigations.blank? %>
    <%= button_link_to("New #{t('investigation')}", 'arrow_right', new_investigation_path(:create_from_asset=>@study.create_from_asset)) -%>
<% else %>
<h1>New <%= t('study') %></h1>

<div class="show_basic">

	<%= form_for @study do |f| %>
	  <%= render :partial => "form", :locals => { :f => f, :action=>:new } -%>
	<% end -%>
</div>
<% end -%>

app/views/studies/new_investigation_redbox.html.erb
<div id="redbox_contents_div" class="redbox_contents" style="width:400px;">
  <div class="head">
    <%= link_to_close_redbox image_tag("close.gif"), :style => "float:right; margin-left:0.5em; vertical-align:middle;" -%>
    <span style="vertical-align:middle;">
      New <%= t('investigation') %>
    </span>
  </div>
  <div class="center-block body">
    <div id="errorExplanation" class="errorExplanation" style="display:none;"></div>

    Creating a new <%= t('investigation') %> for the <%= t('project') %> <b>'<%= h(@investigation.projects.first.name) %>'</b>

    <%= hidden_field_tag :project_id,@investigation.projects.first.id %>

    <p>
      <%= label_tag :title %><br/>
      <%= text_field_tag :title,'',:size=>42 %>
    </p>
    <p>
      <%= label_tag :description %><br/>
      <%= text_area_tag :description,'',:cols=>40,:rows=>5 %>
    </p>

    <input type="button" value="Cancel" onclick="javascript: RedBox.close(); return(false);" />
    <%= submit_tag "Create",:onclick=>"postInvestigationData();return(false);" %>
  </div>
</div>

app/views/studies/show.html.erb
<%= render :partial => "general/item_title",:locals => {:item=>@study, :buttons_partial => 'studies/buttons'} %>

<div class="row">
  <div class="col-md-9 col-sm-8 box_about_actor">
    <%= item_description @study.description -%>

    <div class="row">
      <div class="col-md-6">

        <%= persistent_resource_id(@study) %>

        <p class="investigation">
          <label><%= t('investigation') %>:</label>
          <%= investigation_link(@study.investigation) %>
        </p>

        <%= render :partial => 'projects/show_project_relationship', :locals => {:resource => @study}%>

        <p>
          <label><%= t('person_responsible').capitalize %>:</label>
          <% if @study.person_responsible.try :can_view? -%>
              <%= link_to @study.person_responsible.name,@study.person_responsible %>
          <% else -%>
              <span class="none_text">Not available</span>
          <% end -%>
        </p>

        <p>
          <b>Experimentalists:</b>
          <%= text_or_not_specified(@study.experimentalists) %>
        </p>

      </div>
    </div>
    <%= render :partial=>"general/isa_graph", :locals => {:root_item => @study, :deep => false, :include_parents => true} %>
  </div>

  <div class="col-md-3 col-sm-4">
    <%= render :partial=>"assets/resource_main_content_right",:locals => { :resource => @study, :creators => (@study.creators | [@study.contributing_user.try(:person)]).compact.uniq } %>
  </div>
</div>


<%= render :partial=>"general/items_related_to", :object => @study %>