config/routes.rb
      post :check_related_items
      post :check_gatekeeper_required
      get :download
      get :published
      post :publish_related_items
      post :publish
      post :request_resource
      post :update_annotations_ajax
      post :new_version
      delete :destroy_version
      get :isa_children
    end
    resources :content_blobs do
      member do
        get :view_pdf_content
        get :view_content
        get :get_pdf
        get :download
      end
    end
    resources :people,:projects,:publications,:events,:only=>[:index]
  end

  resources :models do
    collection do
      get :typeahead
      get :preview
      post :test_asset_url
      post :items_for_result
      post :resource_in_tab
    end
    member do
      get :compare_versions
      post :compare_versions
      post :check_related_items
      get :visualise
      post :check_gatekeeper_required
      get :download
      get :matching_data
      get :published
      post :publish_related_items
      post :new_version
      post :submit_to_sycamore
      post :export_as_xgmml
      post :update_annotations_ajax
      post :publish
      post :execute
      post :request_resource
      get :simulate
      post :simulate
      delete :destroy_version
      post :mint_doi
      get :mint_doi_confirm
      get :isa_children
    end
    resources :model_images do
      collection do
        post :new
      end
      member do
        post :select
      end
    end

    resources :content_blobs do
      member do
        get :view_pdf_content
        get :view_content
        get :get_pdf
        get :download
      end
    end
    resources :people,:projects,:investigations,:assays,:studies,:publications,:events,:only=>[:index]
  end

  resources :sops do
    collection do
      get :typeahead
      get :preview
      post :test_asset_url
      post :items_for_result
      post :resource_in_tab
    end
    member do
      post :check_related_items
      post :check_gatekeeper_required
      get :download
      get :published
      post :publish_related_items
      post :publish
      post :request_resource
      post :update_annotations_ajax
      post :new_version
      delete :destroy_version
      post :mint_doi
      get :mint_doi_confirm
      get :isa_children
    end
    resources :experimental_conditions do
      collection do
        post :create_from_existing
      end
    end
    resources :content_blobs do
      member do
        get :view_pdf_content
        get :view_content
        get :get_pdf
        get :download
      end
    end
    resources :people,:projects,:investigations,:assays,:samples,:studies,:publications,:events,:only=>[:index]
  end

  resources :content_blobs, :except => [:show, :index, :update, :create, :destroy] do
    collection do
      post :examine_url
    end
  end
  resources :programmes do
    resources :avatars do
      member do
        post :select
      end
    end
    collection do
      post :items_for_result
      get :awaiting_activation
    end
    member do
      get :initiate_spawn_project
      get :activation_review
      put :accept_activation
      put :reject_activation
      get :reject_activation_confirmation
      post :spawn_project
      get :storage_report
      get :isa_children
    end
    resources :people,:projects, :institutions, :investigations, :studies, :assays,
              :data_files, :models, :sops, :presentations, :events, :publications
  end

  resources :publications do
    collection do
      get :typeahead
      get :preview
      get :query_authors
      get :query_authors_typeahead
      get :export
      post :fetch_preview
      post :items_for_result
      post :resource_in_tab
    end
    member do
      post :update_annotations_ajax
      post :disassociate_authors
    end
    resources :people,:projects,:investigations,:assays,:studies,:models,:data_files,:events,:only=>[:index]
  end

  resources :events do
    collection do
      get :typeahead
      get :preview
      post :items_for_result
      post :resource_in_tab
    end
    resources :people,:projects,:data_files,:publications,:presentations,:only=>[:index]
  end

  resource :policies do
    collection do
      post :preview_permissions
    end
  end

  resources :spreadsheet_annotations, :only => [:create, :destroy, :update]


  resources :strains do
    collection do
      get :existing_strains_for_assay_organism
      get :strains_of_selected_organism
      post :items_for_result
      post :resource_in_tab
    end
    member do
      post :update_annotations_ajax
    end
    resources :specimens,:assays,:people,:projects,:samples,:only=>[:index]
  end

  resources :organisms do
    collection do
      post :search_ajax
      post :resource_in_tab
    end
    resources :projects,:assays,:studies,:models,:strains,:specimens,:only=>[:index]
    member do
      get :visualise
    end
  end

  resources :tissue_and_cell_types
  resources :statistics do
    collection do
      get :application_status
    end
  end

  resources :workflows do
    collection do
      get :typeahead
      post :test_asset_url
    end

    member do
      get :download
      get :describe_ports
      post :temp_link
      post :new_version
      post :update_annotations_ajax
      post :check_related_items
      post :publish
      get :published
      post :favourite
      delete :favourite_delete
      post :mint_doi
      get :mint_doi_confirm
    end

    resources :runs, :controller => 'taverna_player/runs'
  end

  resources :runs, :controller => 'taverna_player/runs', :only => ['edit', 'update'] do
    member do
      post :report_problem
    end
  end

  resources :group_memberships

  resources :sweeps do
    member do
      put :cancel
      get :runs
      post :download_results
      get :view_result
    end
  end

  resources :site_announcements do
    collection do
      get :feed
      get :notification_settings
      post :update_notification_settings
    end
  end

  ### SAMPLES ###

  resources :samples do
    collection do
      get :attribute_form
      get :preview
      get :filter
    end
    member do
      post :update_annotations_ajax
      get :isa_children
    end
  end

  ### SAMPLE TYPES ###

  resources :sample_types do
    collection do
      post :create_from_template
      get :select
      get :filter_for_select
    end
    member do
      get :template_details
    end
    resources :samples
    resources :content_blobs do
      member do
        get :download
      end
    end
  end

  ### SAMPLE CONTROLLED VOCABS ###

  resources :sample_controlled_vocabs

  ### ASSAY AND TECHNOLOGY TYPES ###

  get '/assay_types/',:to=>"assay_types#show",:as=>"assay_types"
  get '/modelling_analysis_types/',:to=>"assay_types#show",:as=>"modelling_analysis_types"
  get '/technology_types/',:to=>"technology_types#show",:as=>"technology_types"


  ### MISC MATCHES ###
  match '/search/' => 'search#index', :as => :search
  match '/search/save' => 'search#save', :as => :save_search
  match '/search/delete' => 'search#delete', :as => :delete_search
  match '/search/items_for_result' => 'search#items_for_result', :via => :post
  match 'svg/:id.:format' => 'svg#show', :as => :svg
  match '/tags/latest' => 'tags#latest', :as => :latest_tags
  match '/tags/query' => 'tags#query', :as => :query_tags
  match '/tags' => 'tags#index', :as => :all_tags
  match '/tags/:id' => 'tags#show', :as => :show_tag
  match '/tags' => 'tags#index', :as => :all_anns
  match '/tags/:id' => 'tags#show', :as => :show_ann
  match '/jerm/' => 'jerm#index', :as => :jerm
  match '/jerm/fetch' => 'jerm#fetch', :as=>:jerm
  match '/countries/:country_name' => 'countries#show', :as => :country

  match '/data_fuse/' => 'data_fuse#show', :as => :data_fuse
  match '/favourite_groups/new' => 'favourite_groups#new', :as => :new_favourite_group, :via => :post
  match '/favourite_groups/create' => 'favourite_groups#create', :as => :create_favourite_group, :via => :post
  match '/favourite_groups/edit' => 'favourite_groups#edit', :as => :edit_favourite_group, :via => :post
  match '/favourite_groups/update' => 'favourite_groups#update', :as => :update_favourite_group, :via => :post
  match '/favourite_groups/:id' => 'favourite_groups#destroy', :as => :delete_favourite_group, :via => :delete
  match 'studies/new_investigation_redbox' => 'studies#new_investigation_redbox', :as => :new_investigation_redbox, :via => :post
  match 'experiments/create_investigation' => 'studies#create_investigation', :as => :create_investigation, :via => :post
  match '/work_groups/review/:type/:id/:access_type' => 'work_groups#review_popup', :as => :review_work_group, :via => :post
  match ':controller/:id/approve_or_reject_publish' => ":controller#show"

  match '/signup' => 'users#new', :as => :signup

  match '/logout' => 'sessions#destroy', :as => :logout
  match '/login' => 'sessions#new', :as => :login
  match '/auth/:provider/callback' => 'sessions#create'
  match '/activate/:activation_code' => 'users#activate', :activation_code => nil, :as => :activate
  match '/forgot_password' => 'users#forgot_password', :as => :forgot_password
  match '/policies/request_settings' => 'policies#send_policy_data', :as => :request_policy_settings
  match '/fail'=>'fail#index',:as=>:fail,:via=>:get

  #feedback
  match '/home/feedback' => 'homes#feedback', :as=> :feedback, :via=>:get

  #tabber lazy load
  match 'application/resource_in_tab' => 'application#resource_in_tab'

  #error rendering
  match "/404" => "errors#error_404"
  match "/422" => "errors#error_422"
  match "/500" => "errors#error_500"

  match "/zenodo_oauth_callback" => "zenodo/oauth2/callbacks#callback"

  get "/citation/*doi(.:format)" => "citations#fetch", :as => :citation

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.

app/helpers/spreadsheet_helper.rb
module SpreadsheetHelper
  include Seek::Data::SpreadsheetExplorerRepresentation

  def generate_paginate_rows(rows, sheet_index, per_page)
    # need to record the index of the nil row, for later use
    rows_with_index = []
    rows = rows.drop(1) if rows.first.nil?
    rows.each_with_index do |row, index|
      if row.nil?
        rows_with_index << Row.new(index + 1)
      else
        rows_with_index << row
      end
    end

    if sheet_index == params[:sheet].try(:to_i)
      current_page = params[:page].try(:to_i) || 1
    else
      current_page = 1
    end
    WillPaginate::Collection.create(current_page, per_page, rows_with_index.count) do |pager|
      start = (current_page - 1) * per_page # assuming current_page is 1 based.
      pager.replace(rows_with_index[start, per_page]) unless rows_with_index[start, per_page].nil?
    end
  end
end

app/views/spreadsheets/_annotation.html.erb
  <%  if (annotation.attribute.name == "plot_data") -%>
      <%= render :partial=>"spreadsheets/annotation_plot_data",:object=>annotation -%>
  <% else -%>
      <%= render :partial=>"spreadsheets/annotation_text_data",:object=>annotation -%>
  <% end -%>

app/views/spreadsheets/_annotation_form.html.erb
<div id="annotation_form" class="spreadsheet_popup" style="display:none">
  <div class="spreadsheet_box_title">
    <div style="float: left">New Annotation</div>
    <div style="float: right"><a href="#" onclick="$j('#annotation_form').hide(); return false;">Close</a></div>
    <br style="clear:both"/>
  </div>
  <%= form_tag_with_callbacks(spreadsheet_annotations_path,
                {:update => {:success => "annotations", :failure => "spreadsheet_errors"},
                :success => "$j('#spreadsheet_errors').hide();",
                :failure => "$j('#spreadsheet_errors').show();",
                :loading => "Element.show('spinner');$('create_annotation_button').disabled=true;",
                :complete => "Element.hide('spinner');Element.hide('annotation_form');$('create_annotation_button').disabled=false;",
                :id => "new_annotation_form",:remote => true}
                ) do %>
    
    <%= hidden_field_tag :annotation_content_blob_id, @display_data_file.content_blob.id %>
    <%= hidden_field_tag :annotation_sheet_id, "0" %>
    
    <p>
      Cell Range:<br/>
      <%= text_field_tag :annotation_cell_coverage, nil,:class=>"annotation_cell_coverage_class" %>
    </p>

    <p>
      Content:<br/>
      <%= text_area_tag :annotation_content,nil %>
      <%= hidden_field_tag :annotation_attribute_name, "annotation" %>
    </p>
                       
    <%= submit_tag 'Add Annotation',:id=>"create_annotation_button" %>
  <% end %>
  <%= image_tag "ajax-loader.gif", :id => 'spinner', :style => 'display:none;' -%>
</div>

app/views/spreadsheets/_annotation_javascript.html.erb
<script type="text/javascript">
var annotation_sources = [];
var as;

<% annotations.reverse.group_by(&:source).each do |source, annotation_subset| -%>
  as = new annotation_source(<%= source.id -%>, '<%= source.class.name -%>', '<%= source.person.name -%>', '<%= polymorphic_path(source.person) -%>');
  annotation_sources.push(as);
  <% annotation_subset.each do |a| -%>
    as.annotations.push(new annotation(<%= a.id -%>, '<%= a.attribute.name -%>', <%= a.annotatable.worksheet.sheet_number -%>, '<%= a.annotatable.cell_range -%>', '<%= h escape_javascript a.value.text -%>', '<%= time_ago_in_words(a.created_at) -%> ago'));
  <% end -%>
<% end -%>

$j(document).ready(function () {
  var oldAnnotatedCells = $j("td.annotated_cell").removeClass("annotated_cell");

  bindAnnotations(annotation_sources);

  //Flash the annotations that were added/deleted
  var newAnnotatedCells = $j("td.annotated_cell");
  if(newAnnotatedCells != oldAnnotatedCells) {
    oldAnnotatedCells.not(newAnnotatedCells).unbind("click").effect("highlight", {color: "#FF0000"}, 600)
    newAnnotatedCells.not(oldAnnotatedCells).effect("highlight", {color: "#00FF00"}, 600);
  }
});

</script>

app/views/spreadsheets/_annotation_plot_data.html.erb
<% annotation = annotation_plot_data -%>
<div class="annotation annotation_plot_data" id="annotation_<%=annotation.id-%>">
    <%= form_tag(spreadsheet_annotation_path(annotation),
                     {:method => :put,
                     :update => { :success => "annotations", :failure => "spreadsheet_errors"},
                     :success => "$j('#spreadsheet_errors').hide();",
                     :failure => "$j('#spreadsheet_errors').show();",
                     :loading => "$j('#spinner" + annotation.id.to_s + "').show();",
                     :complete => "$j('#spinner" + annotation.id.to_s + "').hide();",
                     :id => "edit_plot_data_form_#{annotation.id}", :remote => true}) do %>

      <div class="annotation_content">
        <div class="annotation_avatar">
          <%= avatar(annotation.source.person, 24) -%>
        </div>
        <div class="annotation_text">
          <%= link_to(annotation.source.person.name, annotation.source.person)%><br/>
        </div>

        <div id="annotation_plot_data_<%= annotation.id -%>">

        </div>
        <div>&nbsp;</div>
        <br style="clear:both"/>

      </div>
      <div class="annotation_footer">
        <div style="float:left"><%= time_ago_in_words(annotation.created_at) %> ago</div>
        <div style="float:right">
          <% if annotation.source == current_user %>
            <%= link_to_with_callbacks(image('spreadsheet_annotation_destroy', :title => "Delete Annotation"),
                       {:url=>{:controller=>"spreadsheet_annotations", :action=>"destroy", :id => annotation.id},
                       :method => :delete,
                       :update => { :success => "annotations", :failure => "spreadsheet_errors"},
                       :loading => "$j('#spinner" + annotation.id.to_s + "').show();",
                       :success => "$j('#spreadsheet_errors').hide();",
                       :failure => "$j('#spreadsheet_errors').show();",
                       :complete => "$j('#spinner" + annotation.id.to_s + "').hide();"},
                       {:remote => true})-%>
            <%= image_tag "ajax-loader.gif", :id => "spinner"+annotation.id.to_s, :class => 'spinner', :style => 'display:none;' -%>
          <% end -%>
          <span class="cell_coverage"><a href="#" onclick="select_range(this.innerHTML);return false;"><%= annotation.annotatable.cell_range -%></a></span>
        </div>
        <br style="clear:both"/>
        <div id="annotation_controls" style="display:none">
          <%= submit_tag 'Save Changes',:id=>"edit_plot_data_button" %> or <%= cancel_button("", :onclick => "toggle_annotation_form('" + annotation.id.to_s + "'); return false;") %>
        </div>
      </div>
      <% end %>
</div>

app/views/spreadsheets/_annotation_text_data.html.erb
<% annotation = annotation_text_data %>
<div class="annotation" id="annotation_<%= annotation.id -%>">
  <%= form_tag_with_callbacks(spreadsheet_annotation_path(annotation),
               {:method => :put,
               :update => {:success => "annotations", :failure => "spreadsheet_errors"},
               :success => "$j('#spreadsheet_errors').hide();",
               :failure => "$j('#spreadsheet_errors').show();",
               :loading => "$j('#spinner" + annotation.id.to_s + "').show();$('edit_annotation_button_#{annotation.id}').disabled=true;",
               :complete => "$j('#spinner" + annotation.id.to_s + "').hide();$('edit_annotation_button_#{annotation.id}').disabled=false;",
               :id => "edit_annotation_form_#{annotation.id}", :remote => true}) do %>

      <div class="annotation_content">
        <div class="annotation_avatar">
          <%= avatar(annotation.source.person, 24) -%>
        </div>
        <div class="annotation_text">
          <%= link_to(annotation.source.person.name, annotation.source.person) %>
          <br/>
          <%= h annotation.value_content %>
          <br/>
        </div>
        <div class="annotation_edit_text" style="display:none;">
          <%= link_to(annotation.source.person.name, annotation.source.person) %>
          <br/>
          <%= text_area_tag :annotation_content, annotation.value_content %>
        </div>
        <br style="clear:both"/>
      </div>
      <div class="annotation_footer">
        <div style="float:left"><%= time_ago_in_words(annotation.created_at) %> ago</div>
        <div style="float:right">
          <% if annotation.source == current_user %>
            <%= link_to_with_callbacks(image('spreadsheet_annotation_destroy', :title => "Delete Annotation"),
                       {       :url=>spreadsheet_annotation_path(annotation),
                               :method => :delete,
                       :update => { :success => "annotations", :failure => "spreadsheet_errors"},
                       :loading => "$j('#spinner" + annotation.id.to_s + "').show();",
                       :success => "$j('#spreadsheet_errors').hide();",
                       :failure => "$j('#spreadsheet_errors').show();",
                       :complete => "$j('#spinner" + annotation.id.to_s + "').hide();"},
                       {:remote => true}) -%>
            <%= link_to(image('spreadsheet_annotation_edit', :title => "Edit Annotation"), '#', :onclick => "toggle_annotation_form('" + annotation.id.to_s + "'); return false;") -%>
            <%= image_tag "ajax-loader.gif", :id => "spinner"+annotation.id.to_s, :class => 'spinner', :style => 'display:none;' -%>
          <% end -%>
          <span class="cell_coverage"><a href="#" onclick="select_range(this.innerHTML);return false;"><%= annotation.annotatable.cell_range -%></a></span>
        </div>
        <br style="clear:both"/>

        <div id="annotation_controls" style="display:none">
          <%= submit_tag 'Save Changes', :id => "edit_annotation_button_#{annotation.id}" %>
          or <%= cancel_button("", :onclick => "toggle_annotation_form('" + annotation.id.to_s + "'); return false;") %>
        </div>
      </div>
  <% end %>
</div>

app/views/spreadsheets/_annotations.html.erb
<div id="annotation_container" style="display:none">
  <div id="annotation_drag"><a href="#" onclick="$j('#annotation_container').hide();">Close</a></div>
  <%= render :partial => "spreadsheets/annotation", :collection => annotations %>
</div>
<div id="annotation_overview" class="spreadsheet_popup" style="display:none">
  <div class="spreadsheet_box_title">
    <div style="float: left">Listing Annotations</div>
    <div style="float: right"><a href="#" onclick="$j('#annotation_overview').hide(); return false;">Close</a></div>
    <br style="clear:both"/>
  </div>
  <table>
    <colgroup><col/><col/><col/></colgroup>
  </table>
</div>

<%= render :partial => "spreadsheets/annotation_javascript", :locals => {:annotations => annotations} %>

app/views/spreadsheets/_export.html.erb
<div id="export_form" class="spreadsheet_popup" style="display:none">
  <div class="spreadsheet_box_title">
    <div style="float: left">Export Selection</div>
    <div style="float: right"><a href="#" onclick="$j('#export_form').hide(); return false;">Close</a></div>
    <br style="clear:both"/>
  </div>
  <p>
    The data in the text box below can be copied and pasted into Microsoft Excel.<br/>
    Make sure when pasting the data, "tabs" are selected as the column delimiter.
  </p>

  <br/>

  <textarea style="width: 25em; height: 20em" id="export_data"></textarea>
</div>

app/views/spreadsheets/_matched_lines.erb
<% unless sheet_array.blank? %>
    <div class="list_item with_smaller_shadow curved">
      <%= list_item_title object %>
      <div id="item_<%= object.id %>">
        <%= render :partial => "spreadsheets/row", :locals => {:sheet_array => sheet_array, :object_id => object.id} %>
        <%= link_to_function ("View more details " + expand_image).html_safe, :style => "background_display: block;", :id => 'show_details_image_' + object.id.to_s do |page|
          page << "if ($('item_#{object.id}_details') === null) {"
          page.insert_html :after, "item_" + object.id.to_s, "<div id='item_#{object.id}_details' style='display: block;'></div>"
          page.replace_html 'item_'+ object.id.to_s + "_details", :partial => "assets/resource_list_item", :locals => {:resource_list_item => object}
          page << "}"
          page << "else {"
          page.visual_effect :toggle_blind, "item_#{object.id}_details", :duration => 0.5
          page << "}"

          page["show_details_image_#{object.id}"].toggle
          page["hide_details_image_#{object.id}"].toggle
        end
        -%>
        <%= link_to_function ("View more details " + collapse_image).html_safe, :style => "display: none;", :id => 'hide_details_image_' + object.id.to_s do |page|
          page.visual_effect :toggle_blind, "item_#{object.id}_details", :duration => 0.5
          page["show_details_image_#{object.id}"].toggle
          page["hide_details_image_#{object.id}"].toggle
        end
        -%>
      </div>
    </div>
<% end %>

app/views/spreadsheets/_plot.html.erb
<div id="plot_panel" class="spreadsheet_popup" style="display:none">
  <div class="spreadsheet_box_title">
    <div style="float: left">Data plot</div>
    <div style="float: right"><a href="#" onclick="$j('#plot_panel').hide(); return false;">Close</a></div>
    <br style="clear:both"/>
  </div>
  

  <div id="plot_data">

  </div>
  <div>&nbsp;</div>

  <%= form_tag_with_callbacks(spreadsheet_annotations_path,
               {       :method=>:post,
                       :update => {:success => "annotations", :failure => "spreadsheet_errors"},
                :success => "$j('#spreadsheet_errors').hide();",
                :failure => "$j('#spreadsheet_errors').show();",
                :loading => "Element.show('spinner_plot');$('store_plot_button').disabled=true;",
                :complete => "Element.hide('spinner_plot');Element.hide('plot_panel');$('store_plot_button').disabled=false;",
                :id => "plot_panel_form",
                :remote => true}) do %>

    <div style="display:none;">
      <%= hidden_field_tag :annotation_content_blob_id, @display_data_file.content_blob.id %>
      <%= hidden_field_tag :annotation_sheet_id, "0" %>

      <%= text_field_tag :annotation_cell_coverage, nil,:class=>"annotation_cell_coverage_class" %>

      <%= text_area_tag :annotation_content,nil,:class=>"annotation_content_class" %>
      <%= hidden_field_tag :annotation_attribute_name, "plot_data" %>
    </div>
    <%= submit_tag('Store as annotation',:id=>"store_plot_button") if logged_in? %>
  <% end %>
  <%= image_tag "ajax-loader.gif", :id => 'spinner_plot', :style => 'display:none;' -%>

</div>

app/views/spreadsheets/_spreadsheet_errors.html.erb
<div class="spreadsheet_errors">
  <h1><%= errors.size > 1 ? "Errors" : "An error"-%> occurred whilst <%= verb -%> your annotation</h1>
  <ul>
    <% errors.each do |attribute, errors_array| %>
      <li><%= errors_array%></li>
    <% end %>
  </ul>
</div>

app/views/spreadsheets/_spreadsheet_styles.html.erb
<style type="text/css" id="generated_spreadsheet_styles">
  <% styles.each_key do |style_name| -%>
    td.<%= style_name -%> {
    <% styles[style_name].attributes.each_key do |a| -%>
      <%#Borders are removed here because they break the table layout in chrome and possibly IE-%>
      <%= a + ": " + styles[style_name][a] + ";" unless a.include?("border")%>
    <% end %>
    }
  <% end %>
</style>
  